version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
  build:
    commands:
      - echo "Restaurando dependencias..."
      - dotnet restore
      - echo "Publicando app..."
      - dotnet publish -c Release -o output
      - printf "web: dotnet Api8.dll\n" > output/Procfile

artifacts:
  files:
    - '**/*'
  base-directory: output

